### ISSUE TITLE
Stack: ghc: unrecognized flag: -Wcompat at startup

### ISSUE THREAD

**Issue by peter-tomaselli** [Gabriella439/list-transformer#12]
Hi there, quite new to practical Haskell developing so apologies if I’m doing something wrong. I cloned down this library because it seemed to be a nice example of writing a small library and I am interested in learning more about the “ListT done right” problem. However, I can’t run the library as cloned in `stack`. I get
```
peter$ stack setup
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
peter$ stack repl
list-transformer> configure (lib)
Configuring list-transformer-1.0.4...
list-transformer> initial-build-steps (lib)
Configuring GHCi with the following packages: list-transformer
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
ghc: unrecognised flag: -Wcompat

Usage: For basic information, try the `--help' option.
```
From what I can tell, stack is attempting to spin up GHC 7.10.3, which does not have a `-Wcompat` flag. But I am not certain how the determination of GHC version is made, if it may have something to do with my system or not, nor do I know exactly when `-Wcompat` was introduced.

For what it’s worth, if I
```diff
diff --git a/list-transformer.cabal b/list-transformer.cabal
index f11ded8..7c18286 100644
--- a/list-transformer.cabal
+++ b/list-transformer.cabal
@@ -26,7 +26,10 @@ library
                      , mtl >= 2.1 && < 2.3
   if !impl(ghc >= 8.0)
     build-depends:     semigroups == 0.18.*
-  ghc-options:         -Wall -Wcompat
+  if !impl(ghc >= 8.0)
+    ghc-options:         -Wall
+  if  impl(ghc >= 8.0)
+    ghc-options:         -Wall -Wcompat  
 
 test-suite doctest
   type: exitcode-stdio-1.0
```
Then I’m all good, but I’m assuming that’s not a great permanent solution.

If you think this problem could possibly affect others and can hint at a clean solution I’d be happy to send a patch.

Thanks for the great blog and content Gabriel!

Peter

**Comment by Gabriella439** [comment]
@peter-tomaselli: Sorry for the delay!  Actually, I think that's a perfectly good solution.  I think that's what many other projects do to work around this problem
