### ISSUE TITLE
Data.List.* functions (in the tutorial)

### ISSUE THREAD

**Issue by chris-martin** [Gabriella439/list-transformer#21]
Using a `ListT` of `()` to induce repetition is demonstrated once in the tutorial...

https://github.com/Gabriel439/Haskell-List-Transformer-Library/blob/aefe568a1fa24d8544502b8698d4b7523038fa5b/src/List/Transformer.hs#L123-L127

What really made it click for me, though, was when I dug up your `replicate` definition out of [an old github comment](https://github.com/Gabriel439/Haskell-List-Transformer-Library/issues/3#issuecomment-238988433).

```haskell
replicate :: Monad m => Int -> m a -> ListT m a
replicate n m = do
    select (Data.List.replicate n ())
    lift m
```

I think this ought to appear somewhere in the tutorial.

What would you think of an expansion to the tutorial's `mapM` explanation...

https://github.com/Gabriel439/Haskell-List-Transformer-Library/blob/aefe568a1fa24d8544502b8698d4b7523038fa5b/src/List/Transformer.hs#L134-L135

... to include some of these additional examples? For `cycle`, for example, it could include the definition you gave,

```haskell
cycle :: Monad m => [m a] -> ListT m a
cycle ms = do
    m <- select (Data.List.cycle ms)
    lift m
```

as well as this one:

```haskell
cycle :: Monad m => ListT m a -> ListT m a
cycle ms = do
    ListT.select (repeat ())
    ms
```

... and so on.

**Comment by Gabriella439** [comment]
Yeah, I'd accept a PR to add those examples
