### ISSUE TITLE
Data.List.* functions?

### ISSUE THREAD

**Issue by mitchellwrosen** [Gabriella439/list-transformer#3]
Do equivalents of e.g. `take`, `drop`, `head`, etc. belong in this library? I assume non-streaming functions like `reverse` definitely do not.

**Comment by Gabriella439** [comment]
Yeah, I think `take` and `drop` are sensible functions to add since they're non-trivial to define.  For `head`, I think the `next` function is probably more desirable in most cases

**Comment by mitchellwrosen** [comment]
Ok. Any others? I just scanned `Data.List` and here's the what I came up with:
- [x] take
- [x] drop 
- [ ] iterate (`(a -> m a) -> a -> ListT m a`)
- [ ] replicate (`Int -> m a -> ListT m a`)
- [ ] cycle
- [x] unfold (`(b -> m (Maybe (a, b))) -> b -> ListT m a`)
- [ ] filter
- [x] zip

**Comment by Gabriella439** [comment]
I checked the ones that I thought couldn't be defined in terms of existing primitives without using explicit recursion.  For the ones that I left unchecked:
- `iterate` can be defined in terms of `unfold`
- `replicate` can be defined in terms of `Data.List.replicate` and `lift`:

``` haskell
replicate :: Monad m => Int -> m a -> ListT m a
replicate n m = do
    select (Data.List.replicate n ())
    lift m
```
- `cycle` can be defined in terms of `Data.List.cycle` and `lift`:

``` haskell
cycle :: Monad m => [m a] -> ListT m a
cycle ms = do
    m <- select (Data.List.cycle ms)
    lift m
```
- `filter` can be defined in terms of `Data.List.filter` and `lift`:

``` haskell
filter :: Monad m => (a -> m Bool) -> ListT m a -> ListT m a
filter pred as = do
    a <- as
    b <- lift (pred a)
    guard b
    return a
```

**Comment by Gabriella439** [comment]
Did you have anything else you wanted to add or is it okay if I go ahead and upload a new release?

**Comment by mitchellwrosen** [comment]
Nope! Go for it.

**Comment by Gabriella439** [comment]
Alright, this is up on Hackage as `list-transformer-1.0.1`.  Thanks again for the contribution! :)

**Comment by mitchellwrosen** [comment]
@Gabriel439 What do you think about adding `nub` as a primitive? I managed to write it with:

```haskell
nub :: (Ord a, Monad m) => ListT m a -> ListT m a
evalStateListT :: Monad m => ListT (StateT s m) a -> s -> ListT m a
hoistListT :: Monad m => (forall x. m x -> n x) -> ListT m a -> ListT n a
```

Seems involved enough to want out-of-the-box, but I also might have missed a means to implement it more simply.

**Comment by Gabriella439** [comment]
I think the only issue with `nub` is that any exact implementation won't run in constant space and I try to avoid exporting any functions that don't stream in constant space
