### ISSUE TITLE
Supporting older GHC versions

### ISSUE THREAD

**Issue by ivanperez-keera** [Gabriella439/list-transformer#32]
Hi,

We are trying to replace an existing module in https://github.com/ivanperez-keera/dunai that depends on the old ListT with one that depends on `list-transformer` (for details, see: https://github.com/ivanperez-keera/dunai/blob/develop-list-transformer/dunai/src/Control/Monad/Trans/MSF/ListTransformer.hs).

Our branch is failing to build because a couple of lines in `ListTransformer.hs` do not include constraints on `Functor` and `Applicative`: https://app.travis-ci.com/github/ivanperez-keera/dunai/jobs/620786761#L748-L779

Dunai (more explicitly, its accompanying bearriver library) mirrors Yampa, which supports all versions of GHC going back to 7.8.

Would you be open to adding these constraints so that we can use `list-transformer` while supporting all versions of GHC that Yampa supports?

**Comment by Gabriella439** [comment]
yeah, i'm fine adding support for older versions of `base` as long as it's with CPP so that the constraint is cleaner for newer versions

**Comment by ivanperez-keera** [comment]
Great!

**Comment by ivanperez-keera** [comment]
On further inspection, I don't think it can be done with additional constraints.

One of the constraints is not in your code, but in a class definition that resides outside of this library. At least not for this error:

```
src/List/Transformer.hs:376:28:
    Could not deduce (Functor m) arising from a use of `fmap'
    from the context (Monad m)
      bound by the type signature for
                 hoist :: Monad m =>
                          (forall a. m a -> n a) -> ListT m b -> ListT n b
      at src/List/Transformer.hs:376:5-53
    Possible fix:
      add (Functor m) to the context of
        the type signature for
          hoist :: Monad m =>
                   (forall a. m a -> n a) -> ListT m b -> ListT n b
    In the first argument of `f', namely `(fmap (hoist f) (next xs))'
    In the first argument of `ListT', namely
      `(f (fmap (hoist f) (next xs)))'
    In the expression: ListT (f (fmap (hoist f) (next xs)))
```

Of course, that line could be replaced with:
```haskell
hoist f xs = ListT (f (next xs >>= \x -> return (hoist f x))) 
```
which does not impose a `Functor` constraint, but I don't know if there are any implications to that change.

The second error:
```
src/List/Transformer.hs:826:21:
    Could not deduce (Applicative m) arising from a use of `pure'
    from the context (Functor (ZipListT m), Monad m)
      bound by the instance declaration
      at src/List/Transformer.hs:823:10-44
    Possible fix:
      add (Applicative m) to the context of
        the type signature for pure :: a -> ZipListT m a
        or the instance declaration
    In the first argument of `ListT', namely `(pure (Cons x go))'
    In the expression: ListT (pure (Cons x go))
    In an equation for `go': go = ListT (pure (Cons x go))
cabal: Failed to build list-transformer-1.1.0 (which is required by
taggingmonad-0.1.0.1, dunai-test-0.12.2 and others). See the build log above
for details.
```

Could also be removed by replacing `go` with:
```haskell
  go = ListT (return (Cons x go))
```

**Comment by Gabriella439** [comment]
I believe changing this:

```haskell
    hoist f xs = ListT (f (fmap (hoist f) (next xs)))
```

… to this:

```haskell
    hoist f xs = ListT (f (next xs >>= \x -> return (hoist f x))) 
```

… is a very safe transformation.  This is because there is a `Monad` law that `m >>= \x -> return (f x) = fmap f m`.

Same thing with the other rewrite you proposed: replacing `pure` with `return` is also a safe transformation.

**Comment by ivanperez-keera** [comment]
@Gabriella439  I've just added a PR. I introduced those alternatives using CPP as instructed. Let me know if you've rather make those changes unconditional.

**Comment by ivanperez-keera** [comment]
Since #33 has been merged, that closes this issue. Thanks!

**Comment by Gabriella439** [comment]
Thank you!!
