### ISSUE TITLE
Collect ListT results

### ISSUE THREAD

**Issue by chshersh** [Gabriella439/list-transformer#7]
It would be really nice to have utility function which converts list-transformer to simple list, something like this:

```haskell
toLinkedList :: Monad m => ListT m a -> m [a]
```

I tried to use some standard functionality, but `fold` from package reverses list:

```haskell
ghci> import qualified List.Transformer as LT
ghci> LT.fold (flip (:)) [] id $ LT.select [1..5]
[ 5 , 4 , 3 , 2 , 1 ]
```

`toList` from `Foldable` doesn't work either, because it loses `m` constraint:

```haskell
ghci> import Data.Foldable
ghci> toList $ LT.select [1..5]
[ 1 , 2 , 3 , 4 , 5 ]
ghci> :t toList $ LT.select [1..5]
toList $ LT.select [1..5] :: (Enum a, Num a) => [a]
```

So I don't know how to easily convert `ListT` to `[]` without writing function with manual pattern-matching. Sorry if this question is too obvious. But I just can't see any way to do this from library tutorial and docs. Thought it seems to me that such use case occur rather often.

**Comment by Gabriella439** [comment]
There is a way to do this, but it's deliberately not advertised:

```haskell
import qualified Control.Foldl
import qualified List.Transformer

toLinkedList = Control.Foldl.purely List.Transformer.fold Control.Foldl.list
```

The reason I don't advertise this is that the library is designed to consume the list incrementally and not materialize the entire list into memory.  The most that the library hints at this is to document that `List.Transformer.fold` can be used with any `Fold` from the `foldl` library via `purely`

**Comment by chshersh** [comment]
Thanks for clarification! I think it would be great to have such words said in documentation explicitly. Now I see only this:

> These lines stream in constant space, never retaining more than one line in memory:

For me it means that this library can be used to generate constant space stream while in reality but, as I far as I understand, it **should** be used only like this. So the motivation is not only to create `ListT`-done-right but also make it act like a stream which is another goal.

**Comment by Gabriella439** [comment]
I created a pull request adding this explanation to the documentation.  Let me know if that is what you had in mind: https://github.com/Gabriel439/Haskell-List-Transformer-Library/pull/8

**Comment by chshersh** [comment]
@Gabriel439 Exactly! This explains everything in excellent way. Thanks for your amazing work!

**Comment by Gabriella439** [comment]
You're welcome! :)
